schema_version: 1

context:
  name: wiscopy
  version: "0.1.3"
  python_min: '3.10'

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/wiscopy-${{ version }}.tar.gz
  sha256: 1b62082d091f79bce47082eca5ad9266f619f18a9186cb3fbec3651200e68738

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python ${{ python_min }}.*
    - pip
    - hatchling
  run:
    - python >=${{ python_min }}
    - pydantic >=2.10.6
    - httpx >=0.28.1
    - pandas >=2.2.3

tests:
  - python:
      imports:
        - wiscopy
      pip_check: true
      python_version: ${{ python_min }}.*

about:
  license: MIT
  license_file: LICENSE
  summary: Python wrapper for Wisconet
  homepage: https://github.com/UW-Madison-DSI/wiscopy
  repository: https://github.com/UW-Madison-DSI/wiscopy

extra:
  recipe-maintainers:
    - matthewfeickert
    - ilmcconnell
